/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./apps/routes/__root";

// Create Virtual Routes

const IndexLazyImport = createFileRoute("/")();
const LoginIndexLazyImport = createFileRoute("/login/")();

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
	path: "/",
	getParentRoute: () => rootRoute,
} as unknown).lazy(() =>
	import("./apps/routes/index.lazy").then((d) => d.Route),
);

const LoginIndexLazyRoute = LoginIndexLazyImport.update({
	path: "/login/",
	getParentRoute: () => rootRoute,
} as unknown).lazy(() =>
	import("./apps/routes/login.index.lazy").then((d) => d.Route),
);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/": {
			id: "/";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof IndexLazyImport;
			parentRoute: typeof rootRoute;
		};
		"/login/": {
			id: "/login/";
			path: "/login";
			fullPath: "/login";
			preLoaderRoute: typeof LoginIndexLazyRoute;
			parentRoute: typeof rootRoute;
		};
	}
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
	IndexLazyRoute,
	LoginIndexLazyRoute,
});

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/login/": {
      "filePath": "login.index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
